plazas:
    type: rest
    prefix: plazas
    resource: ApiBundle\Controller\PlazaController
estacionamientos:
    type: rest
    prefix: estacionamientos
    resource: ApiBundle\Controller\EstacionamientoController
viapublica:
    type: rest
    prefix: viapublica
    resource: ApiBundle\Controller\EstacionamientoViaPublicaController
normativas:
    type: rest
    prefix: normativas
    resource: ApiBundle\Controller\NormativaController